sudo : required 
services: 
        - docker
script:
            - cd web_grep && docker build -t mc . 
            
            - cd web_grep &&  docker run -v /home:/app/mc  -e FILE_NAME='/product_test.xlsx' -it mc   

          
